steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/pdf-app", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/pdf-app"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/pdf-app
  - --location=us-central1-c
  - --cluster=pdf-app
  - --namespace=pdf-app-prod


options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: '297818405395-compute@developer.gserviceaccount.com'
