apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-app-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-app
  template:
    metadata:
      labels:
        app: pdf-app
    spec:
      containers:
      - name: pdf-app-gke
        image: gcr.io/cloud-chef-439008/pdf-app 
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "pdf-app-gke-service"
  namespace: "pdf-app-prod"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "pdf-app"
  type: "LoadBalancer"
